import {
  Armchair,
  ArrowDownToLine,
  ArrowLeftRight,
  Baby,
  Backpack,
  BedDouble,
  BedSingle,
  Bike,
  Car,
  ChefHat,
  CookingPot,
  Eye,
  Footprints,
  Hand,
  HeartHandshake,
  Luggage,
  Monitor,
  MonitorUp,
  MoveUp,
  PersonStanding,
  Plane,
  Route,
  Ruler,
  Scale,
  ScanFace,
  ShoppingBag,
  ShowerHead,
  Smartphone,
  Sofa,
  TrafficCone,
  type LucideIcon,
} from 'lucide-react'
import type { ErgoCategoryId } from '@/types/recovery'

export const CATEGORY_ICONS: Record<ErgoCategoryId, LucideIcon> = {
  desk: Monitor,
  sleep: BedDouble,
  devices: Smartphone,
  driving: Car,
  cooking: CookingPot,
  bathing: ShowerHead,
  travel: Plane,
  childcare: Baby,
  shopping: ShoppingBag,
  cycling: Bike,
}

/** One glyph per habit, so the checklist reads at a glance without detail lines. */
export const TASK_ICONS: Record<string, LucideIcon> = {
  monitor_height_checked: MonitorUp,
  monitor_distance_set: Ruler,
  forearms_supported: Armchair,
  rule_20_20_20: Eye,
  sleeping_position_adhered: BedDouble,
  pillow_aligned: BedSingle,
  device_eye_level: Smartphone,
  headrest_contact: Car,
  hands_9_3: Hand,
  red_light_chin_tucks: TrafficCone,
  mirrors_not_twist: ArrowLeftRight,
  cutting_board_raised: ChefHat,
  footstool_dishes: Footprints,
  heavy_pots_waist: CookingPot,
  shower_lean_forward: ShowerHead,
  squat_at_sink: ArrowDownToLine,
  mirror_eye_level: ScanFace,
  u_pillow_used: Plane,
  travel_walk_breaks: Footprints,
  luggage_rolled_beside: Luggage,
  child_held_close: HeartHandshake,
  squat_to_lift_child: ArrowDownToLine,
  feeding_pillow_used: Sofa,
  loads_balanced: Scale,
  backpack_used: Backpack,
  chores_no_overhead: MoveUp,
  handlebars_raised: Bike,
  chin_tuck_at_stops: PersonStanding,
  smooth_short_rides: Route,
}
